describe('LOGIN', () => {
  it('standard user', () => {
    cy.visit('https://www.saucedemo.com/')
    cy.get('[data-test="username"]').type('standard_user')
    cy.get('[data-test="password"]').type('secret_sauce')
    cy.get('[data-test="login-button"]').click()
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
    cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
    cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').click()
    cy.get('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').click()
    cy.get('[data-test="add-to-cart-sauce-labs-onesie"]').click()
    cy.get('[data-test="shopping-cart-link"]').click()
    cy.get('[id="checkout"]').click()
    cy.get('#first-name').type('Toyib')
    cy.get('#last-name').type('Balogun')
    cy.get('[data-test="postalCode"]').type('10023')
    cy.get('#continue').click()
    cy.get('[name="finish"]').click()
    cy.get('[data-test="back-to-products"]').click()
    cy.get('#react-burger-menu-btn').click()
    cy.get('#logout_sidebar_link').click()
    
  })
})